# 101GenAI Platform Configuration
# This file drives the entire Terraform deployment

# Cloud Provider Configuration
provider: "aws"  # Options: "aws" or "gcp"
region: "ap-south-1"  # AWS: ap-south-1, us-east-1, etc. | GCP: asia-south1, us-central1, etc.
environment: "production"

# Domain Mapping
domains:
  frontend: "https://app.101genai.com"
  backend: "https://api.101genai.com"
  keycloak: "https://auth.101genai.com"
  weaviate: "https://vector.101genai.com"

# Cluster Configuration
cluster_name: "101genai-platform-cluster"

# For GCP deployments only
gcp_project_id: "your-gcp-project-id"  # Required only when provider is "gcp"

# Node Configuration
nodes:
  machine_type: "t3a.xlarge"  # AWS: t3a.xlarge, m5.large, etc. | GCP: e2-standard-4, n1-standard-4, etc.
  node_count: 3

# Services Configuration
services:
  # Database Services
  mongodb:
    enabled: true
    replicas: 3
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
    storage:
      size: "20Gi"
      access_modes: ["ReadWriteOnce"]
    # Secret reference: mongodb-secret (to be created manually in secret manager)
    env:
      MONGO_INITDB_DATABASE: "101genai"

  postgres:
    enabled: true
    replicas: 1
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
    storage:
      size: "10Gi"
      access_modes: ["ReadWriteOnce"]
    # Secret reference: postgres-secret (to be created manually in secret manager)
    env:
      POSTGRES_DB: "keycloak"
      PGDATA: "/var/lib/postgresql/data/pgdata"

  redis:
    enabled: true
    replicas: 2  # 1 master + 1 replica
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
    storage:
      size: "5Gi"
      access_modes: ["ReadWriteOnce"]
    env:
      REDIS_MAXMEMORY: "200mb"
      REDIS_MAXMEMORY_POLICY: "allkeys-lru"
      REDIS_APPENDONLY: "yes"

  # Vector Database
  weaviate:
    enabled: true
    replicas: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
    storage:
      size: "32Gi"
      access_modes: ["ReadWriteOnce"]
    env:
      QUERY_DEFAULTS_LIMIT: "25"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "false"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: "text2vec-openai,text2vec-cohere,text2vec-huggingface,ref2vec-centroid,generative-openai,qna-openai"
      CLUSTER_HOSTNAME: "node1"

  # Authentication Service
  keycloak:
    enabled: true
    replicas: 1
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
    # Secret reference: keycloak-secret (to be created manually in secret manager)
    env:
      KC_DB: "postgres"
      KC_HOSTNAME: "auth.101genai.com"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: "edge"

  # Application Services
  backend:
    enabled: true
    replicas: 2
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
    env:
      # Application Settings
      DEBUG: "false"
      ALLOWED_HOSTS: "api.101genai.com,localhost"
      
      # Celery Configuration
      CELERY_WORKER_CONCURRENCY: "4"
      CELERY_WORKER_PREFETCH_MULTIPLIER: "1"
      
      # Email Configuration
      EMAIL_HOST: "smtp.gmail.com"
      EMAIL_PORT: "587"
      EMAIL_USE_TLS: "true"
      
      # Application Metadata
      APP_NAME: "101GenAI Backend"
      APP_VERSION: "1.0.0"
      LOG_LEVEL: "INFO"

  frontend:
    enabled: true
    replicas: 2
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
    env:
      # Authentication
      NEXT_PUBLIC_KEYCLOAK_REALM: "101genai"
      NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: "101genai-frontend"
      
      # Application Settings
      NODE_ENV: "production"
      NEXT_PUBLIC_APP_NAME: "101GenAI Platform"
      NEXT_PUBLIC_APP_VERSION: "1.0.0"

  # Worker Services
  celery:
    enabled: true
    replicas: 2
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
    env:
      # Celery Configuration
      CELERY_WORKER_CONCURRENCY: "4"
      CELERY_WORKER_PREFETCH_MULTIPLIER: "1"
      
      # Application Settings
      DEBUG: "false"
      LOG_LEVEL: "INFO"
      APP_NAME: "101GenAI Celery Worker"
      APP_VERSION: "1.0.0"

hpa_config:
  enabled: true
  min_replicas: 1
  max_replicas: 10
  target_cpu_utilization: 70
  target_memory_utilization: 80

secret_manager:
  provider: "aws"  # Options: "aws", "gcp", "vault"
  region: "ap-south-1"
  secrets:
    # These secrets need to be created manually in AWS Secrets Manager
    mongodb_secret: "101genai/mongodb/credentials"
    postgres_secret: "101genai/postgres/credentials" 
    keycloak_secret: "101genai/keycloak/credentials"
    redis_secret: "101genai/redis/credentials"
    backend_secrets: "101genai/backend/secrets"
    frontend_secrets: "101genai/frontend/secrets"
    celery_secrets: "101genai/celery/secrets"
